CREATE DATABASE ESCOLA;
SHOW DATABASES;
USE ESCOLA;
DROP DATABASE ESCOLA;

DROP DATABASE DETRAN;
CREATE DATABASE DETRAN;

USE DETRAN;

CREATE TABLE PROPRIETARIO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR (150) NOT NULL,
    DT_NASC DATE NOT NULL
);

CREATE TABLE VEICULO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR (150) NOT NULL,
    PLACA VARCHAR (8) NOT NULL,
    ID_P INT NOT NULL,
    FOREIGN KEY(ID_P) REFERENCES
    PROPRIETARIO(ID)
);

INSERT INTO PROPRIETARIO(NOME, DT_NASC) VALUES('LARISSA', '2004-10-27');

SELECT * FROM PROPRIETARIO;

INSERT INTO VEICULO(NOME, PLACA, ID_P) VALUES('GOL', 'AAA-2025', 1);

SELECT * FROM VEICULO;
