CREATE DATABASE ESCOLA;
SHOW DATABASES;
USE ESCOLA;
DROP DATABASE ESCOLA;

DROP DATABASE DETRAN;
CREATE DATABASE DETRAN;

USE DETRAN;

CREATE TABLE PROPRIETARIO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR (150) NOT NULL,
    DT_NASC DATE NOT NULL
);

CREATE TABLE VEICULO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR (150) NOT NULL,
    PLACA VARCHAR (8) NOT NULL,
    ID_P INT NOT NULL,
    FOREIGN KEY(ID_P) REFERENCES
    PROPRIETARIO(ID)
);

INSERT INTO PROPRIETARIO(NOME, DT_NASC) VALUES('LARISSA', '2004-10-27');
INSERT INTO PROPRIETARIO(NOME, DT_NASC) VALUES('DEBORA', '2007-09-10');

SELECT * FROM PROPRIETARIO;

INSERT INTO VEICULO(NOME, PLACA, ID_P) VALUES('GOL', 'AAA-2025', 1);
INSERT INTO VEICULO(NOME, PLACA, ID_P) VALUES('UNO', 'BBB-2025', 2);

SELECT * FROM VEICULO;

SELECT NOME FROM PROPRIETARIO;
SELECT PLACA FROM VEICULO;

SELECT NOME AS 'NOME DO VEÍCULO' FROM VEICULO;

SELECT NOME FROM PROPRIETARIO WHERE DT_NASC = '2004-10-27' OR ID = 1;
SELECT NOME, MAX(DT_NASC) FROM PROPRIETARIO;
SELECT MAX(DT_NASC) AS 'DATA DE NASCIMENTO' FROM PROPRIETARIO;

SELECT NOME, MIN(DT_NASC) FROM PROPRIETARIO;

SELECT SUM(ID) FROM PROPRIETARIO;

SELECT COUNT(*) FROM PROPRIETARIO;
SELECT COUNT(*) FROM VEICULO;

SELECT MAX(DT_NASC) FROM PROPRIETARIO;
SELECT MIN(DT_NASC) FROM PROPRIETARIO;

/* SELECT SUM(EXPRESSAO) FROM PROPRIETARIO */
/* SELECT AVG(EXPRESSAO) FROM PROPRIETARIO */

