CREATE DATABASE INTERNET;
USE INTERNET;

CREATE TABLE PACOTES(
	ID_PACOTE INT PRIMARY KEY AUTO_INCREMENT,
    VELOCIDADE VARCHAR (45),
    DATA_INICIO DATE,
    MENSALIDADE FLOAT,
    ID_DEPTO INT NOT NULL,
    FOREIGN KEY(ID_DEPTO) REFERENCES
    DEPARTAMENTO(ID_DEPARTAMENTO)
);

CREATE TABLE DEPARTAMENTO(
	ID_DEPARTAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR (45)
);

CREATE TABLE CLIENTES(
	ID_CLIENTES INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR (45),
    SOBRENOME VARCHAR (45),
    DATA_NASCIMENTO DATE,
    DATA_CADASTRO DATE,
    CIDADE VARCHAR (45),
    ESTADO CHAR(2),
    ENDERECO VARCHAR (45),
    TELEFONE VARCHAR (45),
    CELULAR VARCHAR (45),
    DESCONTO_MENSAL VARCHAR (45),
    ID_PAC INT NOT NULL,
    FOREIGN KEY(ID_PAC) REFERENCES
    PACOTES(ID_PACOTE)
);

CREATE TABLE CATEGORIA_PACOTE(
	ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR (45),
    PRECO_MIN FLOAT,
    PRECO_MAX FLOAT
);
