/* LARISSA ALVES DE SOUZA */

CREATE DATABASE INTERNET;
USE INTERNET;

CREATE TABLE PACOTES(
    ID_PACOTE INT PRIMARY KEY AUTO_INCREMENT,
    VELOCIDADE VARCHAR (45),
    DATA_INICIO DATE,
    MENSALIDADE FLOAT,
    ID_DEPTO INT NOT NULL,
    FOREIGN KEY(ID_DEPTO) REFERENCES
    DEPARTAMENTO(ID_DEPARTAMENTO)
);

CREATE TABLE DEPARTAMENTO(
    ID_DEPARTAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR (45)
);

CREATE TABLE CLIENTES(
    ID_CLIENTES INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR (45),
    SOBRENOME VARCHAR (45),
    DATA_NASCIMENTO DATE,
    DATA_CADASTRO DATE,
    CIDADE VARCHAR (45),
    ESTADO CHAR(2),
    ENDERECO VARCHAR (45),
    TELEFONE VARCHAR (45),
    CELULAR VARCHAR (45),
    DESCONTO_MENSAL VARCHAR (45),
    ID_PAC INT NOT NULL,
    FOREIGN KEY(ID_PAC) REFERENCES
    PACOTES(ID_PACOTE)
);

CREATE TABLE CATEGORIA_PACOTE(
    ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR (45),
    PRECO_MIN FLOAT,
    PRECO_MAX FLOAT
);

INSERT INTO DEPARTAMENTO(NOME) VALUES('Vendas');
INSERT INTO DEPARTAMENTO(NOME) VALUES('Suporte Técnico');
INSERT INTO DEPARTAMENTO(NOME) VALUES('Financeiro');
INSERT INTO DEPARTAMENTO(NOME) VALUES('Marketing');
INSERT INTO DEPARTAMENTO(NOME) VALUES('Recursos Humanos');

INSERT INTO PACOTES(VELOCIDADE, DATA_INICIO, MENSALIDADE, ID_DEPTO) VALUES('50', '2025-01-01', 99.90, 1);
INSERT INTO PACOTES(VELOCIDADE, DATA_INICIO, MENSALIDADE, ID_DEPTO) VALUES('100', '2025-01-01', 149.90, 2);
INSERT INTO PACOTES(VELOCIDADE, DATA_INICIO, MENSALIDADE, ID_DEPTO) VALUES('200', '2025-01-01', 199.90, 3);
INSERT INTO PACOTES(VELOCIDADE, DATA_INICIO, MENSALIDADE, ID_DEPTO) VALUES('500', '2025-01-01', 249.90, 4);
INSERT INTO PACOTES(VELOCIDADE, DATA_INICIO, MENSALIDADE, ID_DEPTO) VALUES('1000', '2025-01-01', 349.90, 5);

INSERT INTO CLIENTES(NOME, SOBRENOME, DATA_NASCIMENTO, DATA_CADASTRO, CIDADE, ESTADO, ENDERECO, TELEFONE, CELULAR, DESCONTO_MENSAl, ID_PAC) VALUES('Larissa', 'Souza', '2004-10-27', '2025-05-01', 'Bauru', 'SP', 'Rua das Flores, 123', '(14) 98765-4321', '(14) 91234-5678', '10', 5);
INSERT INTO CLIENTES(NOME, SOBRENOME, DATA_NASCIMENTO, DATA_CADASTRO, CIDADE, ESTADO, ENDERECO, TELEFONE, CELULAR, DESCONTO_MENSAl, ID_PAC) VALUES('Ana', 'Costa', '1990-11-25', '2025-05-02', 'Rio de Janeiro', 'RJ', 'Avenida Atlântica, 456', '(21) 99876-5432', '(21) 92345-6789', '15', 2);
INSERT INTO CLIENTES(NOME, SOBRENOME, DATA_NASCIMENTO, DATA_CADASTRO, CIDADE, ESTADO, ENDERECO, TELEFONE, CELULAR, DESCONTO_MENSAl, ID_PAC) VALUES('Lucas', 'Oliveira', '1995-03-18', '2025-05-03', 'Sao Paulo', 'SP', 'Rua dos Três, 789', '(31) 98765-4321', '(31) 91999-8888', '5', 3);
INSERT INTO CLIENTES(NOME, SOBRENOME, DATA_NASCIMENTO, DATA_CADASTRO, CIDADE, ESTADO, ENDERECO, TELEFONE, CELULAR, DESCONTO_MENSAl, ID_PAC) VALUES('Mariana', 'Souza', '1992-05-02', '2025-05-04', 'Curitiba', 'PR', 'Rua Paraná, 101', '(41) 98877-6655', '(41) 91234-7890', '20', 4);
INSERT INTO CLIENTES(NOME, SOBRENOME, DATA_NASCIMENTO, DATA_CADASTRO, CIDADE, ESTADO, ENDERECO, TELEFONE, CELULAR, DESCONTO_MENSAl, ID_PAC) VALUES('José', 'Pereira', '1980-09-30', '2025-05-05', 'Porto Alegre', 'RS', 'Rua das Acácias, 202', '(51) 97766-5544', '(51) 91345-6789', '10', 1);

INSERT INTO CATEGORIA_PACOTE(NOME, PRECO_MIN, PRECO_MAX) VALUES('Básico', 50.00, 100.00);
INSERT INTO CATEGORIA_PACOTE(NOME, PRECO_MIN, PRECO_MAX) VALUES('Intermediário', 101.00, 200.00);
INSERT INTO CATEGORIA_PACOTE(NOME, PRECO_MIN, PRECO_MAX) VALUES('Avançado', 201.00, 300.00);
INSERT INTO CATEGORIA_PACOTE(NOME, PRECO_MIN, PRECO_MAX) VALUES('Premium', 301.00, 500.00);
INSERT INTO CATEGORIA_PACOTE(NOME, PRECO_MIN, PRECO_MAX) VALUES('Ultra', 501.00, 1000.00);

/* 1) Mostre o estado e o número de clientes de cada estado. */
SELECT ESTADO, COUNT(ESTADO) AS 'QUANTIDADE EM CADA ESTADO' FROM CLIENTES GROUP BY ESTADO;

/* 2) Mostre a velocidade de internet e a média de pagamento mensal para cada velocidade. */
SELECT VELOCIDADE, AVG(MENSALIDADE) AS 'MÉDIA DE PAGAMENTO MENSAL' FROM PACOTES GROUP BY VELOCIDADE;

/* 3) Mostre o estado e o número de cidades para cada estado. */
SELECT ESTADO, COUNT(CIDADE) AS 'QUANTIDADE DE CIDADES EM CADA ESTADO' FROM CLIENTES GROUP BY ESTADO;

/* 4) Mostre o número do departamento (Departamento_departamentoid) e o maior pagamento mensal por departamento. */
SELECT ID_DEPTO, MAX(MENSALIDADE) AS 'MAIOR PAGAMENTO MENSAL POR DEPARTAMENTO' FROM PACOTES GROUP BY ID_DEPTO;

/* 5) Mostre o número do pacote (pacoteid) e a média de desconto mensal para cada pacote. */
SELECT ID_PAC, AVG(DESCONTO_MENSAL) AS 'MÉDIA DE DESCONTO MENSAL PARA CADA PACOTE' FROM CLIENTES GROUP BY ID_PAC;

/* 6) Mostre o número do pacote (pacoteid) e a média de desconto mensal para cada pacote, apenas para pacotes cujos números sejam iguais a 22 ou 13. */
SELECT ID_PAC, AVG(DESCONTO_MENSAL) AS 'MÉDIA DE DESCONTO MENSAL PARA CADA PACOTE' FROM CLIENTES GROUP BY ID_PAC HAVING AVG(DESCONTO_MENSAL) = 22 OR AVG(DESCONTO_MENSAL) = 13;

/* 7) Mostre o maior, o menor e a média mensal de pagamento para cada velocidade de internet. */
SELECT MAX(MENSALIDADE) AS 'MAIOR PAGAMENTO MENSAL', MIN(MENSALIDADE) AS 'MENOR PAGAMENTO MENSAL', AVG(MENSALIDADE) AS 'MEDIA MENSAL DE PAGAMENTO' FROM PACOTES GROUP BY VELOCIDADE;

/* 8) Mostre a velocidade de internet e o número do pacote para cada velocidade de internet, apenas para velocidades de internet acima de 200Mb. */
SELECT VELOCIDADE, ID_PACOTE FROM PACOTES GROUP BY VELOCIDADE HAVING VELOCIDADE > 200;
